name: Snake Animation

on:
workflow_dispatch:

permissions:
contents: write

jobs:
snake:
runs-on: ubuntu-latest

```
steps:
  - uses: actions/checkout@v4

  - name: Generate snake
    uses: Platane/snk@v3
    with:
      github_user_name: shibchandan
      outputs: dist/snake.svg

  - name: Deploy
    uses: JamesIves/github-pages-deploy-action@v4
    with:
      branch: output
      folder: dist
```
